/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardTeachersRouteImport } from './routes/(dashboard)/teachers'
import { Route as dashboardStudentsRouteImport } from './routes/(dashboard)/students'
import { Route as dashboardSpecialtiesRouteImport } from './routes/(dashboard)/specialties'
import { Route as dashboardScheduleRouteImport } from './routes/(dashboard)/schedule'
import { Route as dashboardGroupsRouteImport } from './routes/(dashboard)/groups'
import { Route as dashboardGradesRouteImport } from './routes/(dashboard)/grades'
import { Route as dashboardDisciplinesRouteImport } from './routes/(dashboard)/disciplines'
import { Route as dashboardCurriculumsRouteImport } from './routes/(dashboard)/curriculums'
import { Route as dashboardAnalyticsRouteImport } from './routes/(dashboard)/analytics'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardTeachersRoute = dashboardTeachersRouteImport.update({
  id: '/(dashboard)/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardStudentsRoute = dashboardStudentsRouteImport.update({
  id: '/(dashboard)/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSpecialtiesRoute = dashboardSpecialtiesRouteImport.update({
  id: '/(dashboard)/specialties',
  path: '/specialties',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardScheduleRoute = dashboardScheduleRouteImport.update({
  id: '/(dashboard)/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardGroupsRoute = dashboardGroupsRouteImport.update({
  id: '/(dashboard)/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardGradesRoute = dashboardGradesRouteImport.update({
  id: '/(dashboard)/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDisciplinesRoute = dashboardDisciplinesRouteImport.update({
  id: '/(dashboard)/disciplines',
  path: '/disciplines',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardCurriculumsRoute = dashboardCurriculumsRouteImport.update({
  id: '/(dashboard)/curriculums',
  path: '/curriculums',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAnalyticsRoute = dashboardAnalyticsRouteImport.update({
  id: '/(dashboard)/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/analytics': typeof dashboardAnalyticsRoute
  '/curriculums': typeof dashboardCurriculumsRoute
  '/disciplines': typeof dashboardDisciplinesRoute
  '/grades': typeof dashboardGradesRoute
  '/groups': typeof dashboardGroupsRoute
  '/schedule': typeof dashboardScheduleRoute
  '/specialties': typeof dashboardSpecialtiesRoute
  '/students': typeof dashboardStudentsRoute
  '/teachers': typeof dashboardTeachersRoute
  '/': typeof dashboardIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/analytics': typeof dashboardAnalyticsRoute
  '/curriculums': typeof dashboardCurriculumsRoute
  '/disciplines': typeof dashboardDisciplinesRoute
  '/grades': typeof dashboardGradesRoute
  '/groups': typeof dashboardGroupsRoute
  '/schedule': typeof dashboardScheduleRoute
  '/specialties': typeof dashboardSpecialtiesRoute
  '/students': typeof dashboardStudentsRoute
  '/teachers': typeof dashboardTeachersRoute
  '/': typeof dashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/login': typeof authLoginRoute
  '/(dashboard)/analytics': typeof dashboardAnalyticsRoute
  '/(dashboard)/curriculums': typeof dashboardCurriculumsRoute
  '/(dashboard)/disciplines': typeof dashboardDisciplinesRoute
  '/(dashboard)/grades': typeof dashboardGradesRoute
  '/(dashboard)/groups': typeof dashboardGroupsRoute
  '/(dashboard)/schedule': typeof dashboardScheduleRoute
  '/(dashboard)/specialties': typeof dashboardSpecialtiesRoute
  '/(dashboard)/students': typeof dashboardStudentsRoute
  '/(dashboard)/teachers': typeof dashboardTeachersRoute
  '/(dashboard)/': typeof dashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/analytics'
    | '/curriculums'
    | '/disciplines'
    | '/grades'
    | '/groups'
    | '/schedule'
    | '/specialties'
    | '/students'
    | '/teachers'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/curriculums'
    | '/disciplines'
    | '/grades'
    | '/groups'
    | '/schedule'
    | '/specialties'
    | '/students'
    | '/teachers'
    | '/'
  id:
    | '__root__'
    | '/(auth)/login'
    | '/(dashboard)/analytics'
    | '/(dashboard)/curriculums'
    | '/(dashboard)/disciplines'
    | '/(dashboard)/grades'
    | '/(dashboard)/groups'
    | '/(dashboard)/schedule'
    | '/(dashboard)/specialties'
    | '/(dashboard)/students'
    | '/(dashboard)/teachers'
    | '/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLoginRoute: typeof authLoginRoute
  dashboardAnalyticsRoute: typeof dashboardAnalyticsRoute
  dashboardCurriculumsRoute: typeof dashboardCurriculumsRoute
  dashboardDisciplinesRoute: typeof dashboardDisciplinesRoute
  dashboardGradesRoute: typeof dashboardGradesRoute
  dashboardGroupsRoute: typeof dashboardGroupsRoute
  dashboardScheduleRoute: typeof dashboardScheduleRoute
  dashboardSpecialtiesRoute: typeof dashboardSpecialtiesRoute
  dashboardStudentsRoute: typeof dashboardStudentsRoute
  dashboardTeachersRoute: typeof dashboardTeachersRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/teachers': {
      id: '/(dashboard)/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof dashboardTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/students': {
      id: '/(dashboard)/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof dashboardStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/specialties': {
      id: '/(dashboard)/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof dashboardSpecialtiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/schedule': {
      id: '/(dashboard)/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof dashboardScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/groups': {
      id: '/(dashboard)/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof dashboardGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/grades': {
      id: '/(dashboard)/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof dashboardGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/disciplines': {
      id: '/(dashboard)/disciplines'
      path: '/disciplines'
      fullPath: '/disciplines'
      preLoaderRoute: typeof dashboardDisciplinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/curriculums': {
      id: '/(dashboard)/curriculums'
      path: '/curriculums'
      fullPath: '/curriculums'
      preLoaderRoute: typeof dashboardCurriculumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/analytics': {
      id: '/(dashboard)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof dashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authLoginRoute: authLoginRoute,
  dashboardAnalyticsRoute: dashboardAnalyticsRoute,
  dashboardCurriculumsRoute: dashboardCurriculumsRoute,
  dashboardDisciplinesRoute: dashboardDisciplinesRoute,
  dashboardGradesRoute: dashboardGradesRoute,
  dashboardGroupsRoute: dashboardGroupsRoute,
  dashboardScheduleRoute: dashboardScheduleRoute,
  dashboardSpecialtiesRoute: dashboardSpecialtiesRoute,
  dashboardStudentsRoute: dashboardStudentsRoute,
  dashboardTeachersRoute: dashboardTeachersRoute,
  dashboardIndexRoute: dashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
